# This is the argocd-server deployment which runs the Argo CD API/UI
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-server
    spec:
      containers:
      - name: argocd-server
        image: argoproj/argocd:latest
        ports:
        - containerPort: 8080
        - containerPort: 8083
        
---        
# Argocd-repo-server deployment which runs the git repository server
apiVersion: apps/v1
kind: Deployment  
metadata:
  name: argocd-repo-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-repo-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-repo-server
    spec:
      containers:
      - name: argocd-repo-server
        image: argoproj/argocd:latest
        ports:
        - containerPort: 8081
        
---
# Argocd-redis deployment for Argo CD redis database        
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-redis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-redis
    spec:
      containers:
      - name: argocd-redis
        image: redis:6.0.8
        
---        
# Argocd-dex-server deployment for Argo CD dex server (handles Argo CD SSO)
apiVersion: apps/v1  
kind: Deployment
metadata:
  name: argocd-dex-server  
spec:
  replicas: 1
  selector:
    matchLabels:
     app.kubernetes.io/name: argocd-dex-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-dex-server
    spec:
      containers:
      - name: argocd-dex-server
        image: quay.io/dexidp/dex:v2.27.0
        
# The following components are services to expose the above deployments        
---
apiVersion: v1
kind: Service
metadata:
  name: argocd-server
spec:
  selector:
    app.kubernetes.io/name: argocd-server
  ports:
  - port: 80
    targetPort: 8080
    
---  
apiVersion: v1
kind: Service  
metadata:
  name: argocd-repo-server
spec:
  selector:
    app.kubernetes.io/name: argocd-repo-server
  ports:
  - port: 8081
    targetPort: 8081
    
---
apiVersion: v1  
kind: Service
metadata: 
  name: argocd-redis
spec:
  selector:
    app.kubernetes.io/name: argocd-redis
  ports:
  - port: 6379
    targetPort: 6379
    
---
apiVersion: v1
kind: Service
metadata:
  name: argocd-dex-server
spec:
  selector:
    app.kubernetes.io/name: argocd-dex-server  
  ports:
  - port: 5556
    targetPort: 5556